//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace watchmen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("watchmen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choppers.
        /// </summary>
        public static string ARMAHOLIC_CHOPPERS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_CHOPPERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        public static string ARMAHOLIC_GEAR {
            get {
                return ResourceManager.GetString("ARMAHOLIC_GEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Armors.
        /// </summary>
        public static string ARMAHOLIC_HEAVY_ARMORS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_HEAVY_ARMORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Armors.
        /// </summary>
        public static string ARMAHOLIC_LIGHT_ARMORS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_LIGHT_ARMORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string ARMAHOLIC_MISCELLANEOUS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_MISCELLANEOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string ARMAHOLIC_OBJECTS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packs.
        /// </summary>
        public static string ARMAHOLIC_PACKS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_PACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes.
        /// </summary>
        public static string ARMAHOLIC_PLANES {
            get {
                return ResourceManager.GetString("ARMAHOLIC_PLANES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Packs.
        /// </summary>
        public static string ARMAHOLIC_REPLACEMENT_PACKS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_REPLACEMENT_PACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea.
        /// </summary>
        public static string ARMAHOLIC_SEA {
            get {
                return ResourceManager.GetString("ARMAHOLIC_SEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string ARMAHOLIC_SOUNDS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_SOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrains.
        /// </summary>
        public static string ARMAHOLIC_TERRAINS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_TERRAINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string ARMAHOLIC_UNITS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Packs.
        /// </summary>
        public static string ARMAHOLIC_VEHICLE_PACK {
            get {
                return ResourceManager.GetString("ARMAHOLIC_VEHICLE_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string ARMAHOLIC_WEAPONS {
            get {
                return ResourceManager.GetString("ARMAHOLIC_WEAPONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheeled.
        /// </summary>
        public static string ARMAHOLIC_WHEELED {
            get {
                return ResourceManager.GetString("ARMAHOLIC_WHEELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégsem.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Létrehozás dátuma:.
        /// </summary>
        public static string create_date {
            get {
                return ResourceManager.GetString("create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nap.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üres az addon lista, nincs mit elmenteni!.
        /// </summary>
        public static string empty_addon_list {
            get {
                return ResourceManager.GetString("empty_addon_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string FILE_META_LINE_CHARACTER {
            get {
                return ResourceManager.GetString("FILE_META_LINE_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string FILE_SEPARATOR_CHARACTER {
            get {
                return ResourceManager.GetString("FILE_SEPARATOR_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string file_write {
            get {
                return ResourceManager.GetString("file_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leválogatás dátuma:.
        /// </summary>
        public static string limit_date {
            get {
                return ResourceManager.GetString("limit_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betöltés.
        /// </summary>
        public static string load_addons {
            get {
                return ResourceManager.GetString("load_addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Művelet folyamatban.
        /// </summary>
        public static string long_operation {
            get {
                return ResourceManager.GetString("long_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hónap.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem várjon....
        /// </summary>
        public static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        public static string save_addons {
            get {
                return ResourceManager.GetString("save_addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weboldal felolvasás.
        /// </summary>
        public static string search_start {
            get {
                return ResourceManager.GetString("search_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Év.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
    }
}
